# .uplift.yml
# Example of bumping a package.json file

bumps:
  - file: package.json
    json:
      - path: "version"
        semver: true
commitAuthor:
  name: "yuval-bot"
  email: "yuval-bot@gmail.com"

commitMessage: "chore(release): this is a custom release message"
